name: result_dart
description: Result for dart. It is an implementation based on Kotlin Result and Swift Result.
version: 2.0.0
repository: https://github.com/Flutterando/result_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: any
  very_good_analysis: ^5.1.0
